name: build
on: [push]
jobs:
  build:
    runs-on: windows-2019
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Bootstrap vcpkg
        shell: bash
        run: ${VCPKG_INSTALLATION_ROOT}/bootstrap-vcpkg.bat
      - name: Install vcpkg dependencies
        run: vcpkg install
      - name: Generate project files with CMake
        shell: bash
        run: |
          cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static .
      - name: Build
        run: cmake --build . --config Release
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: Release/d3d9_uploader.dll
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}-Release
          files: Release/d3d9_uploader.dll
